### ISSUE TITLE
File uploads failing on staging server

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#386]
![]()

**Comment by judelove** [comment]
FIle uploads to tracks on the staging server fail.

**Comment by judelove** [comment]
This is down to how Amazon storage is being mounted. revisit the umask options set on mount!

**Comment by carlosmouracorreia** [comment]
Issue still persists when the server restarts. It's being mounted with wrong permissions when server restarts. See Umask problem.

**Comment by carlosmouracorreia** [comment]
Also, in maybe related news, the media couldn't be played on staging because we're using Apache 2.4 there opposed to 2.2 on production. 

Because of that, different directives for access control had to be written at the /sites-available/ directory.

Further reference:
https://serverfault.com/questions/418101/apache-client-denied-by-server-configuration-despite-allowing-access-to-direc/419317

@judelove

**Comment by carlosmouracorreia** [comment]
Restarted staging server and issue didn't persist anymore, so it might be linked to my previous comment. Will try this tonight on production.
@judelove can you please remind me (so I can maybe write a config script or document it in the wiki) what services need to be manually started on server restart ? (e.g Freeswitch, you said something about the monitor command to open a new terminal session inside the same ssh session)
