### ISSUE TITLE
UI internationalization

### ISSUE THREAD

**Issue by judelove** [rootio/rootio_web#60]
Web UI has provision for language selection but this does not work. Babel was supposed to be used for this. Need to have Portuguese and Romanian versions of the site

**Comment by nightsh** [comment]
Can we possibly use a tool like [Transifex](https://www.transifex.com) for keeping the translations up to date and maybe add more languages later on? They are offering it for free for open source projects and we'd pretty much eliminate the tech barrier for people willing to help with translations.

I can investigate one day if it's worth it and what would it mean for the project and code base. Since our i18n is still in its early stage, my guess is it's better to do it now rather than later.

**Comment by Luthieneye** [comment]
Was this deployed? Pls. send me link, username & pwd

**Comment by csik** [comment]
I8n is built in right now, we had it working from the beginning, just
hadn't done more than cursory translation... Romania may be the only place
where it is necessary so far.

**Comment by nightsh** [comment]
So, the UI i18n is now configured and working. For this task I had to extract all the strings from our code and make them translatable, create two additional languages and compile them.

Additionally, there is now [a Transifex repository](https://transifex.com/rootio/rootio_web/) we can use to track our translation progress, add new contributors and review their work. Transifex allows us to download the files it is generating as .po files and ass them to the code base.

I will close this, even if for now the dynamic build from Transifex is not done. That has more to do with our upcoming CI/CD pipeline and we will deal with it then.
